package com.tc_4.carbon_counter.models;

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;

import org.hibernate.annotations.UpdateTimestamp;

/**
 * Statistics entry for tracking daily values for each user
 */
@Entity
public class DailyStats {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;
 
    @Column(name="user_name")
    String username;

    @Column(name="date")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")    
    @UpdateTimestamp
    LocalDate date;

    @Column(name="water")
    double water;

    @Column(name="power")
    double power;

    @Column(name="miles_driven")
    double milesDriven;

    @Column(name="meat")
    double meat;

    @Column(name="garbage")
    double garbage;

    /**
     * This constructor is meant primarily for testing, the id is normally
     * generated by spring boot and the database so it shouldn't
     * be necessary to have to assign it unless running unit test.
     * @param id
     */
    public DailyStats (Long id){
        this.id = id;
    }

    public DailyStats(){
        super();
    }

//getters----------------------------------

    public Long getId(){
        return id;
    }

    public String getUsername(){
        return username;
    }

    public LocalDate getDate(){
        return date;
    }

    public double getWater(){
        return water;
    }

    public double getPower(){
        return power;
    }

    public double getMilesDriven(){
        return milesDriven;
    }

    public double getMeat(){
        return meat;
    }

    public double getGarbage(){
        return garbage;
    }

//Setters----------------------------------

    public void setUsername(String username){
        this.username = username;
    }

    public void setDate(LocalDate date){
        this.date = date;
    }

    public void setWater(double water){
        this.water = water;
    }

    public void setPower(double power){
        this.power = power;
    }

    public void setMilesDriven(double milesDriven){
        this.milesDriven = milesDriven;
    }

    public void setMeat(double meat){
        this.meat = meat;
    }

    public void setGarbage(double garbage){
        this.garbage = garbage;
    }
//other--------------------------------------

    /**
     * Copy all values (except id) from the provided DailyStats
     * into this one
     * 
     * @param other The stats to copy from
     */
    public void copyFrom(DailyStats other){
        username = other.username;
        date = other.date;
        water = other.water;
        power = other.power;
        milesDriven = other.milesDriven;
        meat = other.meat;
        garbage = other.garbage;
    }

}
